services:
  client:
    build:
      context: ./client
      dockerfile: Containerfile
    environment:
      - TZ=Asia/Tokyo
    # privileged: true
    volumes:
      # comment out when use DooD
      - /var/run/docker.sock:/var/run/docker.sock
      - ./containers:/containers
    networks:
      nt-docker-dind:

networks:
  nt-docker-dind:
